[nmap]
network = 192.168.1.1/24
scan_interval = 300

[database]
db_file = wifi_clients.db

[pushover]
user_key = Your Key
api_token = Your app token

[logging]
log_file = wifi_monitor.log
max_size_mb = 10
backup_count = 5
log_level = INFO
# Enable/disable console logging with loguru
console_logging = true 
