# Project information
site_name: "WiFi Network Monitor"
site_description: "Network monitoring tool with Nmap scanning and Pushover notifications"
site_author: "Your Name"

# Repository
repo_name: "wifi-monitor"
repo_url: "https://github.com/yourusername/wifi-monitor"

# Configuration
theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration:
    - Basic Setup: configuration/setup.md
    - Network Settings: configuration/network.md
    - Pushover Integration: configuration/pushover.md
    - Logging Options: configuration/logging.md
  - Usage:
    - Monitoring: usage/monitoring.md
    - Query Tool: usage/query.md
    - Device Management: usage/devices.md
  - API Reference:
    - WiFi Monitor: api/wifi_monitor.md
    - Query Client: api/query_client.md
  - Security: security.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
      name: Your GitHub

copyright: Copyright &copy; 2024 Your Name 